if (!hasProperty('mainClass')) {
    ext.mainClass = ''
}

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
        }
    }
}
repositories{
    			maven { url 'https://jitpack.io' }
}
dependencies {
    testImplementation project(':jme3-testdata')

    implementation project(':jme3-core')
    implementation project(':jme3-desktop')
    implementation project(':jme3-lwjgl3')
    // compile project(':jme3-bullet-native')
    implementation project(':jme3-terrain')


    implementation 'com.github.polincdev:JesseModel:-SNAPSHOT'
    implementation project(':jme3-effects')

    implementation project(':jme3-jogg')
    implementation project(':jme3-lwjgl3')
    implementation project(':jme3-networking')
    implementation project(':jme3-plugins')
    implementation project(':jme3-testdata')
    
}
